const MAIL_SERVER_API_BASE = "http://localhost:3030"
const MAIL_SERVER_SEND_TICON = MAIL_SERVER_API_BASE + "/send/ticon"
const MAIL_SERVER_SEND_RECEPIENT = MAIL_SERVER_API_BASE + "/send/recipient"

export {
    MAIL_SERVER_API_BASE,
    MAIL_SERVER_SEND_TICON,
    MAIL_SERVER_SEND_RECEPIENT
}